### ISSUE TITLE
This add-on now breaks flashcard review

### ISSUE THREAD

**Issue by rmikedown** [kelciour/movies2anki#23]
After attempting to create a couple decks on my windows anki, the audio stalls and the flashcard deck loads in very slowly and flickers through the deck. When I click out of the review session the audio will finish for the card that was last flipped to.

I uninstall the add-on and the review works as normal. But the cards themselves are messed up. The text repeats on loop.

This problem occurred after using auto-generated subtitles from a VTT subtitle file.

I tried deleting everything including my anki folder and starting over, but the problem keeps occurring now when I install the add-on.

**Comment by kelciour** [comment]
I'm sorry for replying so late and I guess it's no longer important or relevant.

About flashcard load slowness, I don't know what was the issue, but in the latest update I removed the code that was used to change the Id field on card answer if the Audio field was adjusted during review, but it was present for a long time, it was very simple and shouldn't be slow, I didn't receive any similar reports and I can't think of anything else.

About the audio stalls, the add-on creates a new mpv process each time to play a file, it takes a bit of time, but if it's 720p or 1080p, it should be fast enough and not very noticeable, maybe 25-100ms. But for a very large file, I guess, it'd be better to use Tools > Generate Mobile Cards to generate audio and video clips and store them in the collection.media folder so the add-on could play them immediately instead of opening the video file and seeking to the right timestamp.

About "the text repeat on the loop", maybe this is how the subtitles were written in the auto-generated VTT subtitle file.

Anyway, I'll close it, but feel free to reopen it or make a new issue. Thank you for the report!
